"""Synthetic communities, generated from an explicit model of behaviour.

Two uses.

First, validation.  An instrument that cannot tell a broadcast from a
conversation is worthless, and the only way to know is to build communities
whose character is known in advance and check that the measurements recover
it.  The parameters below are the ground truth; `vitals/tests` asserts that
the metrics separate them.

Second, demonstration.  A report can be shown to somebody without touching a
real community's data.

The model is deliberately simple and its assumptions are all visible:

* everyone carries an engagement level that decays every day
* being answered raises it; being ignored after speaking drops it hard
* below a floor, a member stops posting and does not come back
* newcomers speak once, early, and what happens next decides everything

That last point is the whole thesis of the instrument, and it is worth being
explicit that the simulator assumes it rather than proving it.  What the
simulator proves is that *if* communities behave this way, these measurements
can see it.
"""

from __future__ import annotations

import random
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone

from .schema import JOIN, MESSAGE, Community, Event, Member


@dataclass
class Params:
    """The character of a community, stated as numbers."""

    name: str = "synthetic"
    days: int = 120
    surfaces: int = 6
    staff: int = 2
    #: people arriving per day
    arrivals_per_day: float = 6.0
    #: messages a staff member posts per day
    staff_posts_per_day: float = 6.0
    #: chance a newcomer ever says anything at all.  Decided once, when they
    #: arrive, because in practice most people who lurk lurk forever
    speaks_at_all: float = 0.25
    #: chance staff answer a newcomer's first post
    staff_answers: float = 0.5
    #: chance a member answers a newcomer's first post
    member_answers: float = 0.4
    #: when a member speaks, chance they address another member rather than staff
    member_to_member: float = 0.6
    #: daily decay applied to everyone's engagement
    decay: float = 0.06
    #: engagement gained by being answered
    answered_lift: float = 0.35
    #: engagement lost by speaking into silence
    ignored_drop: float = 0.45
    #: a core group that talks mostly to each other
    core: int = 0
    core_intensity: float = 0.0
    #: connectors walk out at the midpoint, to model a community losing its spine
    lose_core_halfway: bool = False
    #: share of the rooms that actually get used.  The rest are the graveyards
    #: every over-built server has
    rooms_used: float = 1.0
    #: days the staff post nothing, as a share.  Without any, there is no way
    #: to see whether the place survives their absence
    staff_off_days: float = 0.2
    #: when a member addresses somebody, how often they do it explicitly.  The
    #: rest of the time the only evidence is that they spoke straight after,
    #: which is the situation in most real servers and the reason the
    #: instrument has to reason about adjacency at all
    mention_rate: float = 0.4
    #: conversation happens in bursts, not uniformly through the day
    sessions_per_day: int = 4
    seed: int = 7


@dataclass
class _Person:
    actor: str
    joined: datetime
    engagement: float
    staff: bool = False
    core: bool = False
    #: decided at arrival: will this person ever post?
    vocal: bool = True
    spoke: bool = False
    gone: bool = False
    partners: set = field(default_factory=set)


def _rate(rng: random.Random, per_day: float) -> int:
    """A crude Poisson draw, good enough to make a plausible day."""
    n = int(per_day)
    return n + (1 if rng.random() < per_day - n else 0)


def generate(params: Params) -> Community:
    rng = random.Random(params.seed)
    start = datetime(2026, 1, 1, tzinfo=timezone.utc)
    surfaces = [f"room-{i + 1}" for i in range(params.surfaces)]
    live_rooms = surfaces[: max(1, int(round(params.surfaces * params.rooms_used)))]
    community = Community(name=params.name, platform="synthetic",
                          surfaces=list(surfaces),
                          notes=["generated by vitals.simulate"])

    people: dict = {}
    for i in range(params.staff):
        actor = f"staff-{i + 1}"
        people[actor] = _Person(actor, start, 1.0, staff=True)
        community.members[actor] = Member(name=actor, staff=True, joined_at=start)

    event_no = 0

    def emit(actor: str, when: datetime, surface: str, parent=None,
             addressed=()) -> Event:
        nonlocal event_no
        event_no += 1
        e = Event(at=when, actor=actor, kind=MESSAGE, surface=surface,
                  id=f"m{event_no}",
                  parent_id=parent.id if parent is not None else "",
                  addressed=tuple(addressed),
                  words=rng.randint(3, 40))
        community.add(e)
        return e

    joined_count = 0
    for day in range(params.days):
        today = start + timedelta(days=day)
        midway = day == params.days // 2

        if midway and params.lose_core_halfway:
            for p in people.values():
                if p.core:
                    p.gone = True

        # arrivals
        for _ in range(_rate(rng, params.arrivals_per_day)):
            joined_count += 1
            actor = f"member-{joined_count}"
            when = today + timedelta(minutes=rng.randint(0, 1439))
            is_core = params.core and joined_count <= params.core
            people[actor] = _Person(
                actor, when,
                rng.uniform(0.45, 0.8) if is_core else rng.uniform(0.2, 0.6),
                core=bool(is_core),
                vocal=is_core or rng.random() < params.speaks_at_all,
            )
            community.members[actor] = Member(name=actor, joined_at=when)
            community.add(Event(at=when, actor=actor, kind=JOIN,
                                id=f"j{joined_count}"))

        # staff broadcast, with days off
        staff_away = rng.random() < params.staff_off_days
        if not staff_away:
            for s in [p for p in people.values() if p.staff]:
                for _ in range(_rate(rng, params.staff_posts_per_day)):
                    at = today + timedelta(minutes=rng.randint(0, 1439))
                    emit(s.actor, at, rng.choice(live_rooms))

        # members.  Conversation happens in bursts: a handful of windows a
        # day, each in one room, with people answering each other minutes
        # apart.  Laying messages out uniformly instead would leave the
        # adjacency evidence untestable, and adjacency is all there is in most
        # real servers.
        live = [p for p in people.values() if not p.staff and not p.gone]
        speaking: list = []
        for p in live:
            p.engagement = max(0.0, p.engagement - params.decay)
            if p.engagement <= 0.05:
                p.gone = True
                continue
            if not p.vocal:
                continue
            debut = not p.spoke
            if debut:
                if (today - p.joined).days > 7 or rng.random() > 0.4:
                    continue
            elif rng.random() > min(0.95, p.engagement):
                continue
            speaking.append((p, debut))

        if speaking:
            rng.shuffle(speaking)
            sessions = max(1, min(params.sessions_per_day, len(speaking)))
            buckets: list = [[] for _ in range(sessions)]
            # the core, if there is one, shares a session: a clique is a
            # clique because its members are in the room at the same time
            core_now = [e for e in speaking if e[0].core]
            others_now = [e for e in speaking if not e[0].core]
            buckets[0] = core_now
            for i, entry in enumerate(others_now):
                buckets[(i % max(1, sessions - 1)) + 1 if sessions > 1 else 0].append(entry)

            for bucket in buckets:
                if not bucket:
                    continue
                core_bucket = any(p.core for p, _ in bucket)
                pool = live_rooms[: max(1, len(live_rooms) // 2)] if core_bucket \
                    else live_rooms
                room = rng.choice(pool)
                clock = today + timedelta(minutes=rng.randint(0, 1200))
                last_speaker = None
                for p, debut in bucket:
                    clock += timedelta(minutes=rng.randint(1, 8))

                    target = None
                    others = [q for q, _ in bucket if q is not p and q.spoke]
                    if last_speaker is not None and last_speaker is not p:
                        target = last_speaker
                    elif p.core and params.core_intensity and \
                            rng.random() < params.core_intensity:
                        core_pool = [q for q in others if q.core]
                        target = rng.choice(core_pool) if core_pool else None
                    elif others and rng.random() < params.member_to_member:
                        target = rng.choice(others)
                    if target is None or rng.random() > params.member_to_member:
                        staff_pool = [q for q in people.values() if q.staff]
                        if staff_pool and rng.random() < 0.5:
                            target = rng.choice(staff_pool)

                    explicit = target is not None and rng.random() < params.mention_rate
                    event = emit(p.actor, clock, room,
                                 addressed=(target.actor,) if explicit else ())
                    if target is not None:
                        p.partners.add(target.actor)
                        target.partners.add(p.actor)
                    last_speaker = p

                    if debut:
                        p.spoke = True
                        answered = False
                        if rng.random() < params.staff_answers:
                            s = rng.choice([q for q in people.values() if q.staff])
                            clock += timedelta(minutes=rng.randint(1, 9))
                            emit(s.actor, clock, room, parent=event,
                                 addressed=(p.actor,))
                            answered = True
                            last_speaker = s
                        helpers = [q for q, _ in bucket if q is not p and q.spoke]
                        if helpers and rng.random() < params.member_answers:
                            h = rng.choice(helpers)
                            clock += timedelta(minutes=rng.randint(1, 9))
                            emit(h.actor, clock, room, parent=event,
                                 addressed=(p.actor,))
                            h.partners.add(p.actor)
                            p.partners.add(h.actor)
                            answered = True
                            last_speaker = h
                        p.engagement += params.answered_lift if answered \
                            else -params.ignored_drop
                        p.engagement = max(0.0, min(1.0, p.engagement))
                    else:
                        p.engagement = min(1.0, p.engagement + 0.05)

    return community.finalise()


#: the three ways a community actually goes wrong, plus the one that works
ARCHETYPES = {
    "broadcast": Params(
        name="broadcast", staff_posts_per_day=14, member_answers=0.03,
        member_to_member=0.05, speaks_at_all=0.06, ignored_drop=0.5,
        surfaces=11, rooms_used=0.45, staff_off_days=0.1, seed=11,
    ),
    "clique": Params(
        name="clique", staff_posts_per_day=4, member_answers=0.05,
        member_to_member=0.75, speaks_at_all=0.10, core=8, core_intensity=0.9,
        arrivals_per_day=7, surfaces=8, rooms_used=0.6, seed=23,
    ),
    "mesh": Params(
        name="mesh", staff_posts_per_day=3, staff_answers=0.35,
        member_answers=0.65, member_to_member=0.75, speaks_at_all=0.28,
        decay=0.035, answered_lift=0.4, surfaces=5, seed=31,
    ),
    "dying": Params(
        name="dying", staff_posts_per_day=3, staff_answers=0.3,
        member_answers=0.55, member_to_member=0.7, speaks_at_all=0.24,
        core=12, core_intensity=0.5, lose_core_halfway=True,
        arrivals_per_day=4, days=140, surfaces=7, rooms_used=0.7, seed=43,
    ),
}


def archetype(name: str) -> Community:
    if name not in ARCHETYPES:
        raise KeyError(f"no archetype {name!r}; try {', '.join(sorted(ARCHETYPES))}")
    return generate(ARCHETYPES[name])
